### 할일 개수 조회
POST localhost:8000/v1/todo/request
Accept: text/event-stream
Connection: keep-alive
content-Type: application/json; charset=utf-8

{
  "prompt": "할일이 얼마나 많이 등록되어 있나요?"
}


### 할일 상세 조회
POST localhost:8000/v1/todo/request
Accept: text/event-stream
Connection: keep-alive
content-Type: application/json; charset=utf-8

{
  "prompt": "등록된 할일 리스트 어떤 것들이 있어?"
}


### 할일 등록
POST localhost:8000/v1/todo/request
Accept: text/event-stream
Connection: keep-alive
content-Type: application/json; charset=utf-8

{
  "prompt": "할일을 등록해줘, 할일은 청소이고, 방청소하는거야, 날짜는 4월 24일이야"
}

### 할일 조회 날짜
POST localhost:8000/v1/todo/request
Accept: text/event-stream
Connection: keep-alive
content-Type: application/json; charset=utf-8

{
  "prompt": "25년 4월 24일에 어떤 일정이 있어?"
}

### 항공 날짜 조회 후 할일 등록
POST localhost:8000/v1/todo/request
Accept: text/event-stream
Connection: keep-alive
content-Type: application/json; charset=utf-8

{
  "prompt": "25년 4월 5일 항공편을 조회해주고 있으면 할일에 25년 4월 5일에 항공 스케줄을 포함해서 일정을 등록해줘"
}


### 4월 5일 할일 조회
POST localhost:8000/v1/todo/request
Accept: text/event-stream
Connection: keep-alive
content-Type: application/json; charset=utf-8

{
  "prompt": "25년 4월 5일 등록된 할일을 알려줘"
}
