### 할일 개수 조회
POST localhost:8000/v1/todo/request
Accept: text/event-stream
Connection: keep-alive
content-Type: application/json; charset=utf-8

{
  "prompt": "할일이 얼마나 많이 등록되어 있나요?"
}


### 할일 상세 조회
POST localhost:8000/v1/todo/request
Accept: text/event-stream
Connection: keep-alive
content-Type: application/json; charset=utf-8

{
  "prompt": "등록된 할일 리스트 어떤 것들이 있어?"
}


### 할일 등록
POST localhost:8000/v1/todo/request
Accept: text/event-stream
Connection: keep-alive
content-Type: application/json; charset=utf-8

{
  "prompt": "할일을 등록해줘, 할일은 청소이고, 방청소하는거야, 날짜는 4월 24일이야"
}

### 할일 조회 날짜
POST localhost:8000/v1/todo/request
Accept: text/event-stream
Connection: keep-alive
content-Type: application/json; charset=utf-8

{
  "prompt": "25년 4월 24일에 어떤 일정이 있어?"
}

### 항공 날짜 조회 후 할일 등록
POST localhost:8000/v1/todo/request
Accept: text/event-stream
Connection: keep-alive
content-Type: application/json; charset=utf-8

{
  "prompt": "25년 4월 5일 항공편을 조회해주고 있으면 할일에 25년 4월 5일에 항공 스케줄을 포함해서 일정을 등록해줘"
}


### 4월 5일 할일 조회
POST localhost:8000/v1/todo/request
Accept: text/event-stream
Connection: keep-alive
content-Type: application/json; charset=utf-8

{
  "prompt": "25년 4월 5일 등록된 할일을 알려줘, html 테이블 형식으로 알려줘"
}


### 새로운 기능을 만들 수 있는지 알아보는 것
POST localhost:8000/v1/todo/request
Accept: text/event-stream
Connection: keep-alive
content-Type: application/json; charset=utf-8

{
  "prompt": "항공권 일정 조회 후 할일에 등록해주는 기능을 만들고 싶은데 현재 가능한지 확인해줄래?"
}

### 항공권 일정 조회 후 주문 후 할일 등록
POST localhost:8000/v1/todo/request
Accept: text/event-stream
Connection: keep-alive
content-Type: application/json; charset=utf-8

{
  "prompt": "25년 4월 25일 방콕으로 가는 비행기편이 있으면 좌석2개를 주문해주고, 할일에 주문 정보를 등록해줘 (주문은 1개만 생성해야해)"
}


### 주문 정보 확인
POST localhost:8000/v1/todo/request
Accept: text/event-stream
Connection: keep-alive
content-Type: application/json; charset=utf-8

{
  "prompt": "주문 아이디 1번에 대해 알려줘"
}
